blank_issues_enabled: false
contact_links:
  - name: Nosso grupo do telegram
    url: https://t.me/tinocanada? 
    about: Qualquer duvida, critica, sugestão, elogio. Lá é onde discutimos quase tudo sobre o Canadá: imigração; como funciona o mundo da TI no país; e até mesmo qual a unidade de medida mais usada (metros? polegadas? bom, já discutimos isso), entre outros assuntos. 
